export const actionTypesSavable = {
  CHANGE_CURRENT_LIST_TITLE: 'CHANGE_CURRENT_LIST_TITLE',
  CHANGE_USER_NAME: 'CHANGE_USER_NAME',
  DELETE_CONNECTION: 'DELETE_CONNECTION',
  CHANGE_NEW_PRODUCT_POSITION: 'CHANGE_NEW_PRODUCT_POSITION',
  REMOVE_LIST: 'REMOVE_LIST',
  POSITION_AS_FIRST: 'POSITION_AS_FIRST',
  SHARE_LIST_WITH_CONNECTION: 'SHARE_LIST_WITH_CONNECTION',
};

export const actionTypesUtil = {
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  PROVIDE_USER_DATA: 'PROVIDE_USER_DATA',
  FETCH_USER: 'FETCH_USER',
  ADD_CONNECTION: 'ADD_CONNECTION',
  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_NEW_LIST: 'ADD_NEW_LIST',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  CLEAR_CURRENT_LIST: 'CLEAR_CURRENT_LIST',
  DELETE_SELECTED_PRODUCTS: 'DELETE_SELECTED_PRODUCTS',
  MARK_PRODUCT_AS_BOUGHT: 'MARK_PRODUCT_AS_BOUGHT',
};
